userland: Use original name libegl-mesa in rdeps
This avoids a missing rdep errors seen sometimes when switching
compilers or graphic driver providers

ERROR: userland-20181120-r0 do_package_qa: QA Issue: /usr/lib/libWFC.so contained in package userland requires li bEGL.so.1, but no providers found in RDEPENDS_userland? [file-rdeps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>